version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: /bin/sh -c "redis-server --port 6379 --requirepass $$REDIS_HOST_PASSWORD"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env

  canto-api:
    restart: unless-stopped
    build:
      context: .
    expose:
      - "3000"  # Internal port exposed to Nginx
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration file
      - ./certs:/etc/ssl/certs              # SSL certificates folder
    depends_on:
      - canto-api

volumes:
  redis-data:
  redis-conf:
